# Generated by Django 4.0.4 on 2022-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oth_images',
            field=models.ManyToManyField(to='product.image'),
        ),
    ]
