# Generated by Django 4.0.4 on 2022-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_oth_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='oth_images',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
