# Generated by Django 4.0.4 on 2022-05-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_image_image_image_oth_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='oth_images',
        ),
    ]
