# Generated by Django 4.0.4 on 2022-05-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_oth_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oth_images',
            field=models.ManyToManyField(to='product.image'),
        ),
    ]
