# Generated by Django 4.0.4 on 2022-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_imagemodel_remove_product_oth_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='oth_images',
        ),
        migrations.AddField(
            model_name='product',
            name='oth_images',
            field=models.ManyToManyField(to='product.image'),
        ),
    ]
