# Generated by Django 4.0.4 on 2022-05-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_image_remove_product_oth_images_product_oth_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oth_images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
