# Generated by Django 4.0.4 on 2022-05-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_imagemodel_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
