# Generated by Django 4.0.4 on 2022-05-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_images_product_image_product_oth_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='p',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oth_images',
        ),
        migrations.AddField(
            model_name='product',
            name='oth_images',
            field=models.ManyToManyField(to='product.images'),
        ),
    ]
