# Generated by Django 4.0.4 on 2022-05-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_images_oth_images_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizes',
            old_name='s_id',
            new_name='s',
        ),
    ]
