# Generated by Django 4.0.4 on 2022-05-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_s_id_sizes_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('красный', 'red'), ('зеленый', 'green'), ('синий', 'blue'), ('желтый', 'yellow'), ('белый', 'white'), ('черный', 'black'), ('фиолетовый', 'violet'), ('коричневый', 'brown'), ('бежевый', 'beige'), ('розовый', 'pink'), ('бирюзовый', 'turquoise'), ('другой', 'other')], max_length=30)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='product.colors'),
        ),
    ]
