# Generated by Django 4.0.4 on 2022-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_colors_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=models.CharField(choices=[('Красный', 'Красный'), ('Зеленый', 'Зеленый'), ('Синий', 'Синий'), ('Желтый', 'Желтый'), ('Белый', 'Белый'), ('Черный', 'Черный'), ('Фиолетовый', 'Фиолетовый'), ('Коричневый', 'Коричневый'), ('Бежевый', 'Бежевый'), ('Розовый', 'Розовый'), ('Бирюзовый', 'Бирюзовый'), ('Другой', 'Другой')], max_length=30),
        ),
    ]
