# Generated by Django 4.0.4 on 2022-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_quantity_alter_colors_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=models.CharField(choices=[('красный', 'красный'), ('зеленый', 'зеленый'), ('синий', 'синий'), ('желтый', 'желтый'), ('оранжевый', 'оранжевый'), ('белый', 'белый'), ('черный', 'черный'), ('фиолетовый', 'фиолетовый'), ('коричневый', 'коричневый'), ('другой', 'другой')], max_length=30),
        ),
    ]
